# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#https://github.com/ngquyn2602/Bai_tap_tri_tue_nhan_tao_AI
import heapq
import itertools
import random
import html
from dataclasses import dataclass
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets


# ============================================================
# 1. CẤU HÌNH MẶC ĐỊNH
# ============================================================

START_DEFAULT = """
1 2 3
4 8 X
7 6 5
"""

GOAL_DEFAULT = """
1 2 3
4 5 6
7 8 X
"""


# ============================================================
# 2. MODEL DỮ LIỆU CHO 8-PUZZLE
# ============================================================

@dataclass
class ChildInfo:
    state: tuple
    move: str
    swapped_tile: int
    g: int
    h: int
    priority: int
    result: str
    note: str


@dataclass
class StepInfo:
    number: int
    status: str
    current: tuple
    g: int
    h: int
    priority: int
    frontier_before: list
    frontier_after: list
    children: list
    reached: list
    expanded: list
    path: list
    moves: list
    messages: list


class PuzzleProblem:
    def __init__(self, goal):
        self.goal = goal
        self.goal_location = self._make_goal_location(goal)

    def parse(self, text):
        text = text.replace(",", " ")
        text = text.replace("/", " ")
        text = text.replace("X", "0")
        text = text.replace("x", "0")

        raw = text.split()

        if len(raw) != 9:
            raise ValueError("Bạn phải nhập đúng 9 ô. Ví dụ: 1 2 3 / 4 8 X / 7 6 5")

        try:
            state = tuple(int(x) for x in raw)
        except:
            raise ValueError("Chỉ được nhập các số 0-8 hoặc X.")

        if set(state) != set(range(9)):
            raise ValueError("Trạng thái phải có đủ 0,1,2,3,4,5,6,7,8 và không được trùng.")

        return state

    def state_to_text(self, state):
        lines = []

        for i in range(0, 9, 3):
            row = []

            for value in state[i:i + 3]:
                row.append("X" if value == 0 else str(value))

            lines.append(" ".join(row))

        return "\n".join(lines)

    def state_to_line(self, state):
        return self.state_to_text(state).replace("\n", " / ")

    def _make_goal_location(self, goal):
        pos = {}

        for index, value in enumerate(goal):
            pos[value] = (index // 3, index % 3)

        return pos

    def inversion_count(self, state):
        arr = [x for x in state if x != 0]
        count = 0

        for i in range(len(arr)):
            for j in range(i + 1, len(arr)):
                if arr[i] > arr[j]:
                    count += 1

        return count

    def can_solve(self, start):
        return self.inversion_count(start) % 2 == self.inversion_count(self.goal) % 2

    def manhattan(self, state):
        total = 0

        for index, value in enumerate(state):
            if value == 0:
                continue

            r = index // 3
            c = index % 3

            gr, gc = self.goal_location[value]

            total += abs(r - gr) + abs(c - gc)

        return total

    def misplaced(self, state):
        wrong = 0

        for current, target in zip(state, self.goal):
            if current != 0 and current != target:
                wrong += 1

        return wrong

    def heuristic(self, state, kind):
        if kind == "MANHATTAN":
            return self.manhattan(state)

        if kind == "MISPLACED":
            return self.misplaced(state)

        return 0

    def expand(self, state):
        blank = state.index(0)
        r = blank // 3
        c = blank % 3

        directions = [
            ("Lên", -1, 0),
            ("Xuống", 1, 0),
            ("Trái", 0, -1),
            ("Phải", 0, 1),
        ]

        children = []

        for move_name, dr, dc in directions:
            nr = r + dr
            nc = c + dc

            if 0 <= nr < 3 and 0 <= nc < 3:
                new_blank = nr * 3 + nc

                temp = list(state)
                tile = temp[new_blank]

                temp[blank], temp[new_blank] = temp[new_blank], temp[blank]

                children.append({
                    "state": tuple(temp),
                    "move": move_name,
                    "tile": tile
                })

        return children


# ============================================================
# 3. SEARCH MACHINE: UCS + GREEDY
# ============================================================

class SearchMachine:
    def __init__(self, problem, start, algorithm, heuristic_kind, max_nodes):
        self.problem = problem
        self.start = start
        self.goal = problem.goal
        self.algorithm = algorithm
        self.heuristic_kind = heuristic_kind
        self.max_nodes = max_nodes

        self.counter = itertools.count()

        self.frontier = []
        self.best_cost = {}
        self.parent = {}
        self.move_record = {}
        self.expanded_set = set()
        self.expanded_order = []
        self.steps = []

    def priority_of(self, g, h):
        if self.algorithm == "UCS":
            return g

        if self.algorithm == "GREEDY":
            return h

        return g

    def active_frontier(self):
        active = []

        for priority, order, state, g in self.frontier:
            if state in self.expanded_set:
                continue

            if self.best_cost.get(state) != g:
                continue

            h = self.problem.heuristic(state, self.heuristic_kind)

            active.append({
                "state": state,
                "g": g,
                "h": h,
                "priority": priority,
                "order": order
            })

        active.sort(key=lambda x: (x["priority"], x["order"]))

        return active

    def reached_snapshot(self):
        data = []

        for state, g in self.best_cost.items():
            data.append({
                "state": state,
                "g": g,
                "h": self.problem.heuristic(state, self.heuristic_kind),
                "parent": self.parent.get(state)
            })

        data.sort(key=lambda x: (x["g"], x["h"], self.problem.state_to_line(x["state"])))

        return data

    def make_path(self, target):
        if target not in self.parent:
            return []

        path = []
        cur = target

        while cur is not None:
            path.append(cur)
            cur = self.parent.get(cur)

        path.reverse()

        return path

    def make_moves(self, target):
        moves = []
        cur = target

        while cur != self.start:
            record = self.move_record.get(cur)

            if record is None:
                break

            moves.append(record)
            cur = record["from"]

        moves.reverse()

        return moves

    def push_start(self):
        g = 0
        h = self.problem.heuristic(self.start, self.heuristic_kind)
        p = self.priority_of(g, h)

        self.best_cost[self.start] = 0
        self.parent[self.start] = None

        heapq.heappush(
            self.frontier,
            (p, next(self.counter), self.start, g)
        )

    def pop_next(self):
        while self.frontier:
            priority, order, state, g = heapq.heappop(self.frontier)

            if state in self.expanded_set:
                continue

            if self.best_cost.get(state) != g:
                continue

            return priority, state, g

        return None, None, None

    def run(self):
        if not self.problem.can_solve(self.start):
            return {
                "status": "UNSOLVABLE",
                "message": "Start và Goal không cùng tính chẵn/lẻ nghịch thế nên không giải được.",
                "steps": []
            }

        self.push_start()

        step_number = 1

        while self.frontier and len(self.expanded_set) < self.max_nodes:
            frontier_before = self.active_frontier()

            current_priority, current_state, current_g = self.pop_next()

            if current_state is None:
                break

            current_h = self.problem.heuristic(current_state, self.heuristic_kind)

            self.expanded_set.add(current_state)
            self.expanded_order.append(current_state)

            current_path = self.make_path(current_state)
            current_moves = self.make_moves(current_state)

            messages = []
            child_logs = []

            if current_state == self.goal:
                if self.algorithm == "UCS":
                    messages.append(
                        "Đã lấy Goal ra khỏi Frontier. Với UCS, đây là đường đi tối ưu vì UCS luôn chọn g(n) nhỏ nhất."
                    )
                else:
                    messages.append(
                        "Đã lấy Goal ra khỏi Frontier. Với Greedy, thuật toán dừng nhưng đường đi chưa chắc tối ưu."
                    )

                frame = StepInfo(
                    number=step_number,
                    status="GOAL",
                    current=current_state,
                    g=current_g,
                    h=current_h,
                    priority=current_priority,
                    frontier_before=frontier_before,
                    frontier_after=self.active_frontier(),
                    children=[],
                    reached=self.reached_snapshot(),
                    expanded=list(self.expanded_order),
                    path=current_path,
                    moves=current_moves,
                    messages=messages
                )

                self.steps.append(frame)

                return {
                    "status": "GOAL",
                    "message": "Tìm thấy Goal.",
                    "cost": current_g,
                    "path": current_path,
                    "moves": current_moves,
                    "steps": self.steps
                }

            for item in self.problem.expand(current_state):
                child = item["state"]
                move = item["move"]
                tile = item["tile"]

                new_g = current_g + 1
                new_h = self.problem.heuristic(child, self.heuristic_kind)
                new_priority = self.priority_of(new_g, new_h)

                if child in self.expanded_set:
                    result = "SKIP"
                    note = "Node con đã nằm trong Expanded nên bỏ qua."

                elif child not in self.best_cost:
                    self.best_cost[child] = new_g
                    self.parent[child] = current_state
                    self.move_record[child] = {
                        "from": current_state,
                        "to": child,
                        "move": move,
                        "tile": tile,
                        "g": new_g,
                        "h": new_h,
                        "priority": new_priority
                    }

                    heapq.heappush(
                        self.frontier,
                        (new_priority, next(self.counter), child, new_g)
                    )

                    result = "ADD"

                    if self.algorithm == "UCS":
                        note = f"Node mới, thêm vào Frontier với priority = g(n) = {new_g}."
                    else:
                        note = f"Node mới, thêm vào Frontier với priority = h(n) = {new_h}."

                elif new_g < self.best_cost[child]:
                    old_g = self.best_cost[child]

                    self.best_cost[child] = new_g
                    self.parent[child] = current_state
                    self.move_record[child] = {
                        "from": current_state,
                        "to": child,
                        "move": move,
                        "tile": tile,
                        "g": new_g,
                        "h": new_h,
                        "priority": new_priority
                    }

                    heapq.heappush(
                        self.frontier,
                        (new_priority, next(self.counter), child, new_g)
                    )

                    result = "UPDATE"
                    note = f"Tìm được đường tốt hơn: g mới = {new_g} nhỏ hơn g cũ = {old_g}."

                else:
                    result = "SKIP"
                    note = f"Không tốt hơn đường cũ trong Reached. g mới = {new_g}, g cũ = {self.best_cost[child]}."

                child_logs.append(
                    ChildInfo(
                        state=child,
                        move=move,
                        swapped_tile=tile,
                        g=new_g,
                        h=new_h,
                        priority=new_priority,
                        result=result,
                        note=note
                    )
                )

                messages.append(
                    f"Di chuyển X {move}, đổi chỗ với ô {tile}: {note}"
                )

            frame = StepInfo(
                number=step_number,
                status="RUNNING",
                current=current_state,
                g=current_g,
                h=current_h,
                priority=current_priority,
                frontier_before=frontier_before,
                frontier_after=self.active_frontier(),
                children=child_logs,
                reached=self.reached_snapshot(),
                expanded=list(self.expanded_order),
                path=current_path,
                moves=current_moves,
                messages=messages
            )

            self.steps.append(frame)
            step_number += 1

        return {
            "status": "LIMIT",
            "message": f"Dừng vì vượt quá giới hạn mở rộng {self.max_nodes} node hoặc Frontier rỗng.",
            "steps": self.steps
        }


# ============================================================
# 4. RANDOM START CHẮC CHẮN GIẢI ĐƯỢC
# ============================================================

def random_start_from_goal(problem, goal, steps):
    state = goal
    previous = None

    for _ in range(steps):
        children = problem.expand(state)

        choices = [
            child for child in children
            if child["state"] != previous
        ]

        if not choices:
            choices = children

        picked = random.choice(choices)

        previous = state
        state = picked["state"]

    return state


# ============================================================
# 5. CSS GIAO DIỆN
# ============================================================

def draw_css():
    display(HTML("""
    <style>
        .new-wrap, .new-wrap * {
            box-sizing: border-box !important;
            font-family: Arial, sans-serif !important;
            color: #111827 !important;
        }

        .new-title {
            background: linear-gradient(135deg, #0f172a, #2563eb, #7c3aed);
            padding: 24px;
            border-radius: 24px;
            box-shadow: 0 12px 28px rgba(15,23,42,0.25);
            margin-bottom: 16px;
        }

        .new-title, .new-title * {
            color: white !important;
        }

        .new-card {
            background: white !important;
            border: 1px solid #d1d5db;
            border-radius: 20px;
            padding: 18px;
            margin: 14px 0;
            box-shadow: 0 6px 18px rgba(15,23,42,0.10);
        }

        .new-section {
            font-size: 22px;
            font-weight: 900;
            margin-bottom: 12px;
        }

        .new-note {
            background: #eff6ff !important;
            border-left: 7px solid #2563eb;
            border-radius: 14px;
            padding: 14px 16px;
            margin: 12px 0;
            font-size: 17px;
            line-height: 1.7;
        }

        .new-warn {
            background: #fff7ed !important;
            border-left: 7px solid #f97316;
            border-radius: 14px;
            padding: 14px 16px;
            margin: 12px 0;
            font-size: 17px;
            line-height: 1.7;
        }

        .new-ok {
            background: #ecfdf5 !important;
            border-left: 7px solid #10b981;
            border-radius: 14px;
            padding: 14px 16px;
            margin: 12px 0;
            font-size: 17px;
            line-height: 1.7;
        }

        .new-flex {
            display: flex;
            flex-wrap: wrap;
            gap: 16px;
            align-items: flex-start;
        }

        .new-board {
            display: grid;
            grid-template-columns: repeat(3, 74px);
            gap: 8px;
            background: #f8fafc !important;
            border: 2px solid #cbd5e1;
            border-radius: 18px;
            padding: 12px;
            width: max-content;
        }

        .new-board-small {
            display: grid;
            grid-template-columns: repeat(3, 46px);
            gap: 5px;
            background: #f8fafc !important;
            border: 1px solid #cbd5e1;
            border-radius: 14px;
            padding: 8px;
            width: max-content;
        }

        .new-cell {
            width: 74px;
            height: 74px;
            background: #dbeafe !important;
            border: 1px solid #93c5fd;
            border-radius: 16px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 30px;
            font-weight: 900;
        }

        .new-cell-small {
            width: 46px;
            height: 46px;
            background: #dbeafe !important;
            border: 1px solid #93c5fd;
            border-radius: 12px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 18px;
            font-weight: 900;
        }

        .new-blank {
            background: #111827 !important;
            color: white !important;
        }

        .new-mini {
            display: inline-block;
            vertical-align: top;
            background: white !important;
            border: 1px solid #d1d5db;
            border-radius: 18px;
            padding: 12px;
            margin: 6px;
            box-shadow: 0 4px 12px rgba(15,23,42,0.08);
        }

        .new-mini-title {
            font-size: 16px;
            font-weight: 900;
            color: #1d4ed8 !important;
            margin-bottom: 8px;
        }

        .new-info {
            font-size: 16px;
            line-height: 1.7;
            margin-top: 8px;
        }

        .new-stat {
            background: #f8fafc !important;
            border: 1px solid #cbd5e1;
            border-radius: 18px;
            padding: 16px;
            min-width: 260px;
            font-size: 19px;
            line-height: 1.9;
        }

        .new-table {
            width: 100%;
            border-collapse: collapse;
            background: white !important;
            font-size: 16px;
        }

        .new-table th {
            background: #111827 !important;
            color: white !important;
            padding: 12px;
            border: 1px solid #374151;
            text-align: left;
        }

        .new-table td {
            background: white !important;
            color: #111827 !important;
            padding: 12px;
            border: 1px solid #d1d5db;
            vertical-align: top;
        }

        .tag-add {
            background: #dcfce7 !important;
            color: #166534 !important;
            padding: 6px 10px;
            border-radius: 999px;
            font-weight: 900;
            display: inline-block;
        }

        .tag-update {
            background: #fef3c7 !important;
            color: #92400e !important;
            padding: 6px 10px;
            border-radius: 999px;
            font-weight: 900;
            display: inline-block;
        }

        .tag-skip {
            background: #fee2e2 !important;
            color: #991b1b !important;
            padding: 6px 10px;
            border-radius: 999px;
            font-weight: 900;
            display: inline-block;
        }
    </style>
    """))


# ============================================================
# 6. HTML COMPONENTS
# ============================================================

def board_html(state, title="", small=False):
    board_class = "new-board-small" if small else "new-board"
    cell_class = "new-cell-small" if small else "new-cell"

    cells = ""

    for value in state:
        if value == 0:
            cells += f'<div class="{cell_class} new-blank">X</div>'
        else:
            cells += f'<div class="{cell_class}">{value}</div>'

    title_html = ""

    if title:
        title_html = f'<div class="new-mini-title">{html.escape(title)}</div>'

    return f"""
    <div>
        {title_html}
        <div class="{board_class}">
            {cells}
        </div>
    </div>
    """


def state_card(problem, item, title):
    return f"""
    <div class="new-mini">
        {board_html(item["state"], title=title, small=True)}
        <div class="new-info">
            g(n): <b>{item["g"]}</b><br>
            h(n): <b>{item["h"]}</b><br>
            priority: <b>{item["priority"]}</b>
        </div>
    </div>
    """


def frontier_view(problem, items, title, limit=8):
    if not items:
        return '<div class="new-note">Frontier rỗng.</div>'

    html_out = '<div class="new-flex">'

    for i, item in enumerate(items[:limit], start=1):
        html_out += state_card(problem, item, f"{title} #{i}")

    html_out += "</div>"

    if len(items) > limit:
        html_out += f"""
        <div class="new-warn">
            Còn {len(items) - limit} trạng thái khác trong Frontier, đã rút gọn để dễ nhìn.
        </div>
        """

    return html_out


def child_view(problem, children):
    if not children:
        return '<div class="new-note">Không có node con vì đã đến Goal hoặc không sinh được node mới.</div>'

    html_out = '<div class="new-flex">'

    for i, child in enumerate(children, start=1):
        if child.result == "ADD":
            tag = '<span class="tag-add">Thêm vào Frontier</span>'
        elif child.result == "UPDATE":
            tag = '<span class="tag-update">Cập nhật tốt hơn</span>'
        else:
            tag = '<span class="tag-skip">Bỏ qua</span>'

        html_out += f"""
        <div class="new-mini">
            {board_html(child.state, title=f"Node con #{i}", small=True)}
            <div class="new-info">
                X đi: <b>{child.move}</b><br>
                Đổi chỗ với ô: <b>{child.swapped_tile}</b><br>
                g(n): <b>{child.g}</b><br>
                h(n): <b>{child.h}</b><br>
                priority: <b>{child.priority}</b><br>
                {tag}<br>
                {html.escape(child.note)}
            </div>
        </div>
        """

    html_out += "</div>"

    return html_out


def reached_table(problem, reached, limit=12):
    if not reached:
        return '<div class="new-note">Reached rỗng.</div>'

    rows = ""

    for i, item in enumerate(reached[:limit], start=1):
        parent = item["parent"]

        if parent is None:
            parent_text = "None"
        else:
            parent_text = problem.state_to_line(parent)

        rows += f"""
        <tr>
            <td><b>{i}</b></td>
            <td>{html.escape(problem.state_to_line(item["state"]))}</td>
            <td><b>{item["g"]}</b></td>
            <td>{item["h"]}</td>
            <td>{html.escape(parent_text)}</td>
        </tr>
        """

    more = ""

    if len(reached) > limit:
        more = f"""
        <div class="new-warn">
            Reached còn {len(reached) - limit} trạng thái khác. Đã rút gọn.
        </div>
        """

    return f"""
    <table class="new-table">
        <tr>
            <th>#</th>
            <th>Trạng thái</th>
            <th>g(n)</th>
            <th>h(n)</th>
            <th>Parent</th>
        </tr>
        {rows}
    </table>
    {more}
    """


def expanded_view(problem, expanded, limit=10):
    if not expanded:
        return '<div class="new-note">Expanded rỗng.</div>'

    html_out = '<div class="new-flex">'

    for i, state in enumerate(expanded[:limit], start=1):
        html_out += f"""
        <div class="new-mini">
            {board_html(state, title=f"Expanded #{i}", small=True)}
        </div>
        """

    html_out += "</div>"

    if len(expanded) > limit:
        html_out += f"""
        <div class="new-warn">
            Expanded còn {len(expanded) - limit} trạng thái khác.
        </div>
        """

    return html_out


def path_view(problem, path, limit=12):
    if not path:
        return '<div class="new-note">Chưa có đường đi.</div>'

    shown = path[-limit:]
    start_index = len(path) - len(shown)

    html_out = '<div class="new-flex">'

    if len(path) > limit:
        html_out += '<div class="new-warn">Đường đi dài nên đã rút gọn các bước đầu.</div>'

    for i, state in enumerate(shown):
        html_out += f"""
        <div class="new-mini">
            {board_html(state, title=f"Bước {start_index + i}", small=True)}
        </div>
        """

    html_out += "</div>"

    return html_out


def moves_table(moves):
    if not moves:
        return '<div class="new-note">Node hiện tại là Start nên chưa có bước di chuyển X.</div>'

    rows = ""

    for i, m in enumerate(moves, start=1):
        rows += f"""
        <tr>
            <td><b>{i}</b></td>
            <td>X đi {m["move"]}</td>
            <td>{m["tile"]}</td>
            <td>{m["g"]}</td>
            <td>{m["h"]}</td>
            <td>{m["priority"]}</td>
        </tr>
        """

    return f"""
    <table class="new-table">
        <tr>
            <th>Bước</th>
            <th>Hành động</th>
            <th>Đổi chỗ với ô</th>
            <th>g(n)</th>
            <th>h(n)</th>
            <th>priority</th>
        </tr>
        {rows}
    </table>
    """


def messages_view(messages):
    if not messages:
        return '<div class="new-note">Không có hành động.</div>'

    rows = ""

    for msg in messages:
        rows += f"<li>{html.escape(msg)}</li>"

    return f"""
    <ul style="font-size:18px; line-height:1.8;">
        {rows}
    </ul>
    """


def history_table(problem, steps, current_index, limit=15):
    rows = ""

    visible = steps[:current_index + 1]
    visible = visible[-limit:]

    for step in visible:
        rows += f"""
        <tr>
            <td><b>{step.number}</b></td>
            <td>{html.escape(problem.state_to_line(step.current))}</td>
            <td>{step.g}</td>
            <td>{step.h}</td>
            <td>{step.priority}</td>
            <td>{len(step.frontier_after)}</td>
            <td>{len(step.reached)}</td>
            <td>{len(step.expanded)}</td>
            <td>{step.status}</td>
        </tr>
        """

    return f"""
    <table class="new-table">
        <tr>
            <th>Bước</th>
            <th>Node đang xét</th>
            <th>g(n)</th>
            <th>h(n)</th>
            <th>priority</th>
            <th>Frontier sau</th>
            <th>Reached</th>
            <th>Expanded</th>
            <th>Trạng thái</th>
        </tr>
        {rows}
    </table>
    """


# ============================================================
# 7. JUPYTER UI
# ============================================================

class ReplayUI:
    def __init__(self):
        self.result = None
        self.steps = []
        self.index = 0
        self.problem = None
        self.start = None
        self.goal = None

        self.algorithm_box = widgets.Dropdown(
            options=[
                ("UCS - Uniform Cost Search", "UCS"),
                ("Greedy Best-First Search", "GREEDY")
            ],
            value="UCS",
            description="Thuật toán:",
            layout=widgets.Layout(width="390px")
        )

        self.heuristic_box = widgets.Dropdown(
            options=[
                ("Manhattan Distance", "MANHATTAN"),
                ("Misplaced Tiles", "MISPLACED")
            ],
            value="MANHATTAN",
            description="Heuristic:",
            layout=widgets.Layout(width="390px")
        )

        self.limit_box = widgets.IntText(
            value=30000,
            description="Max node:",
            layout=widgets.Layout(width="230px")
        )

        self.start_area = widgets.Textarea(
            value=START_DEFAULT.strip(),
            description="Start:",
            layout=widgets.Layout(width="360px", height="120px")
        )

        self.goal_area = widgets.Textarea(
            value=GOAL_DEFAULT.strip(),
            description="Goal:",
            layout=widgets.Layout(width="360px", height="120px")
        )

        self.run_button = widgets.Button(
            description="Chạy lại",
            icon="play",
            button_style="primary",
            layout=widgets.Layout(width="140px")
        )

        self.prev_button = widgets.Button(
            description="Bước trước",
            icon="arrow-left",
            layout=widgets.Layout(width="140px")
        )

        self.next_button = widgets.Button(
            description="Bước tiếp",
            icon="arrow-right",
            button_style="success",
            layout=widgets.Layout(width="140px")
        )

        self.finish_button = widgets.Button(
            description="Chạy hết",
            icon="fast-forward",
            button_style="warning",
            layout=widgets.Layout(width="140px")
        )

        self.random_easy = widgets.Button(
            description="Random dễ",
            button_style="info",
            layout=widgets.Layout(width="120px")
        )

        self.random_medium = widgets.Button(
            description="Random vừa",
            button_style="info",
            layout=widgets.Layout(width="120px")
        )

        self.random_hard = widgets.Button(
            description="Random khó",
            button_style="danger",
            layout=widgets.Layout(width="120px")
        )

        self.output = widgets.Output()

        self.run_button.on_click(self.run)
        self.prev_button.on_click(self.prev_step)
        self.next_button.on_click(self.next_step)
        self.finish_button.on_click(self.finish)

        self.random_easy.on_click(lambda b: self.randomize(8))
        self.random_medium.on_click(lambda b: self.randomize(18))
        self.random_hard.on_click(lambda b: self.randomize(30))

        self.ui = widgets.VBox([
            widgets.HTML("""
            <div class="new-wrap">
                <div class="new-title">
                    <div style="font-size:30px; font-weight:900;">
                        8-Puzzle Search Visualizer
                    </div>
                    <div style="font-size:17px; margin-top:8px;">
                        Bản code mới: cùng logic UCS / Greedy nhưng tổ chức lại thành Problem → SearchMachine → ReplayUI.
                    </div>
                </div>
            </div>
            """),

            widgets.HBox([
                widgets.VBox([
                    self.algorithm_box,
                    self.heuristic_box,
                    self.limit_box,
                    widgets.HBox([
                        self.random_easy,
                        self.random_medium,
                        self.random_hard
                    ]),
                    self.run_button
                ]),
                widgets.VBox([self.start_area]),
                widgets.VBox([self.goal_area])
            ]),

            widgets.HTML("<br>"),

            widgets.HBox([
                self.prev_button,
                self.next_button,
                self.finish_button
            ]),

            self.output
        ])

    def algorithm_name(self):
        if self.algorithm_box.value == "UCS":
            return "UCS - Uniform Cost Search"

        return "Greedy Best-First Search"

    def formula_text(self):
        if self.algorithm_box.value == "UCS":
            return "priority = g(n)"

        return "priority = h(n)"

    def explain_text(self):
        if self.algorithm_box.value == "UCS":
            return """
            UCS chọn node có <b>g(n)</b> nhỏ nhất trong Frontier.
            Vì mỗi bước trong 8-puzzle có cost = 1 nên UCS tìm đường đi ít bước nhất.
            """

        return """
        Greedy chọn node có <b>h(n)</b> nhỏ nhất trong Frontier.
        Greedy nhìn node có vẻ gần Goal nhất, nhưng không đảm bảo tối ưu.
        """

    def randomize(self, depth):
        try:
            temp_problem = PuzzleProblem((1, 2, 3, 4, 5, 6, 7, 8, 0))
            goal = temp_problem.parse(self.goal_area.value)

            problem = PuzzleProblem(goal)
            start = random_start_from_goal(problem, goal, depth)

            self.start_area.value = problem.state_to_text(start)

        except Exception as e:
            with self.output:
                clear_output(wait=True)
                draw_css()
                display(HTML(f"""
                <div class="new-wrap">
                    <div class="new-warn">
                        Lỗi random: {html.escape(str(e))}
                    </div>
                </div>
                """))

    def run(self, button=None):
        with self.output:
            clear_output(wait=True)
            draw_css()

            try:
                temp_problem = PuzzleProblem((1, 2, 3, 4, 5, 6, 7, 8, 0))

                goal = temp_problem.parse(self.goal_area.value)
                self.problem = PuzzleProblem(goal)
                self.goal = goal
                self.start = self.problem.parse(self.start_area.value)

                machine = SearchMachine(
                    problem=self.problem,
                    start=self.start,
                    algorithm=self.algorithm_box.value,
                    heuristic_kind=self.heuristic_box.value,
                    max_nodes=self.limit_box.value
                )

                self.result = machine.run()
                self.steps = self.result["steps"]
                self.index = 0

                self.render()

            except Exception as e:
                display(HTML(f"""
                <div class="new-wrap">
                    <div class="new-warn">
                        Lỗi: {html.escape(str(e))}
                    </div>
                </div>
                """))

    def prev_step(self, button=None):
        if not self.steps:
            return

        self.index = max(0, self.index - 1)
        self.render()

    def next_step(self, button=None):
        if not self.steps:
            return

        self.index = min(len(self.steps) - 1, self.index + 1)
        self.render()

    def finish(self, button=None):
        if not self.steps:
            return

        self.index = len(self.steps) - 1
        self.render()

    def render(self):
        with self.output:
            clear_output(wait=True)
            draw_css()

            if self.result is None:
                return

            if self.result["status"] == "UNSOLVABLE":
                display(HTML(f"""
                <div class="new-wrap">
                    <div class="new-warn">
                        <b>Không giải được puzzle này.</b><br>
                        {html.escape(self.result["message"])}
                    </div>
                </div>
                """))
                return

            if not self.steps:
                display(HTML(f"""
                <div class="new-wrap">
                    <div class="new-warn">
                        {html.escape(self.result["message"])}
                    </div>
                </div>
                """))
                return

            step = self.steps[self.index]

            if step.status == "GOAL":
                status_block = f"""
                <div class="new-ok">
                    Đã tìm thấy Goal.<br>
                    Tổng cost = <b>{self.result.get("cost", step.g)}</b>.<br>
                    Số bước đi = <b>{len(step.path) - 1}</b>.
                </div>
                """
            else:
                status_block = """
                <div class="new-note">
                    Đang chạy từng bước. Bấm <b>Bước tiếp</b> để xem thuật toán mở rộng node kế tiếp.
                </div>
                """

            display(HTML(f"""
            <div class="new-wrap">

                <div class="new-card">
                    <div style="font-size:26px; font-weight:900;">
                        Bước {self.index + 1}/{len(self.steps)}
                    </div>

                    <div style="font-size:18px; line-height:1.8; margin-top:8px;">
                        Thuật toán: <b>{self.algorithm_name()}</b><br>
                        Heuristic: <b>{self.heuristic_box.label}</b><br>
                        Công thức ưu tiên: <b>{self.formula_text()}</b><br>
                        {self.explain_text()}
                    </div>

                    {status_block}
                </div>

                <div class="new-card">
                    <div class="new-section">1. Start - Node đang xét - Goal</div>

                    <div class="new-flex">
                        <div>
                            {board_html(self.start, title="Start", small=False)}
                        </div>

                        <div>
                            {board_html(step.current, title="Node đang xét", small=False)}
                        </div>

                        <div>
                            {board_html(self.goal, title="Goal", small=False)}
                        </div>

                        <div class="new-stat">
                            g(n): <b>{step.g}</b><br>
                            h(n): <b>{step.h}</b><br>
                            priority: <b>{step.priority}</b><br>
                            Frontier sau: <b>{len(step.frontier_after)}</b><br>
                            Reached: <b>{len(step.reached)}</b><br>
                            Expanded: <b>{len(step.expanded)}</b>
                        </div>
                    </div>

                    <div class="new-note">
                        Mục tiêu là biến <b>Start</b> thành đúng <b>Goal</b>.
                        Mỗi lần chỉ được di chuyển ô trống <b>X</b> lên, xuống, trái hoặc phải.
                    </div>
                </div>

                <div class="new-card">
                    <div class="new-section">2. Frontier trước khi lấy node</div>
                    <div class="new-note">
                        Đây là hàng đợi ưu tiên trước khi thuật toán lấy node hiện tại ra để xét.
                    </div>
                    {frontier_view(self.problem, step.frontier_before, "Frontier trước", limit=8)}
                </div>

                <div class="new-card">
                    <div class="new-section">3. Các node con sinh ra</div>
                    <div class="new-warn">
                        Các node con được sinh bằng cách di chuyển ô trống X.
                    </div>
                    {child_view(self.problem, step.children)}
                </div>

                <div class="new-card">
                    <div class="new-section">4. Hành động chi tiết</div>
                    {messages_view(step.messages)}
                </div>

                <div class="new-card">
                    <div class="new-section">5. Frontier sau khi mở rộng node</div>
                    <div class="new-note">
                        Node nào có priority nhỏ nhất sẽ được lấy ra ở bước tiếp theo.
                    </div>
                    {frontier_view(self.problem, step.frontier_after, "Frontier sau", limit=8)}
                </div>

                <div class="new-card">
                    <div class="new-section">6. Reached sau bước này</div>
                    <div class="new-note">
                        Reached lưu các trạng thái đã biết cùng g(n) tốt nhất và Parent của trạng thái đó.
                    </div>
                    {reached_table(self.problem, step.reached, limit=12)}
                </div>

                <div class="new-card">
                    <div class="new-section">7. Expanded sau bước này</div>
                    <div class="new-note">
                        Expanded là các node đã được lấy ra khỏi Frontier và đã xử lý xong.
                    </div>
                    {expanded_view(self.problem, step.expanded, limit=10)}
                </div>

                <div class="new-card">
                    <div class="new-section">8. Đường đi từ Start đến node hiện tại</div>
                    {path_view(self.problem, step.path, limit=12)}
                </div>

                <div class="new-card">
                    <div class="new-section">9. Danh sách bước di chuyển X</div>
                    {moves_table(step.moves)}
                </div>

                <div class="new-card">
                    <div class="new-section">10. Lịch sử tóm tắt</div>
                    {history_table(self.problem, self.steps, self.index, limit=15)}
                </div>

            </div>
            """))


# ============================================================
# 8. KHỞI CHẠY APP
# ============================================================

draw_css()

app = ReplayUI()
display(app.ui)

app.run()