# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# -*- coding: utf-8 -*-
"""
https://github.com/ngquyn2602/Bai_tap_tri_tue_nhan_tao_AI
8 Puzzle - Hill Climbing Algorithms
Thuật toán có trong file:
1. Leo đồi đơn giản / First-choice Hill Climbing
2. Leo đồi dốc nhất / Steepest-ascent Hill Climbing
3. Leo đồi ngẫu nhiên / Stochastic Hill Climbing
4. Leo đồi khởi động lại ngẫu nhiên / Random-restart Hill Climbing

Chạy trong Jupyter / Google Colab:
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Tuple
import random
import html

try:
    from IPython.display import HTML, display, clear_output
    NOTEBOOK_MODE = True
except Exception:
    NOTEBOOK_MODE = False

try:
    import ipywidgets as widgets
    WIDGET_READY = True
except Exception:
    WIDGET_READY = False

Board = Tuple[int, ...]
Move = str


# ============================================================
# 1. CSS HIỂN THỊ
# ============================================================

LIGHT_THEME = """
<style>
.eight-wrap{
    font-family: Arial, sans-serif;
    color:#0f172a;
}
.eight-title{
    font-size:30px;
    font-weight:900;
    margin:12px 0 4px 0;
}
.eight-subtitle{
    font-size:16px;
    color:#475569;
    margin-bottom:14px;
}
.box-note{
    background:#ffffff;
    border:2px solid #dbeafe;
    border-left:8px solid #2563eb;
    border-radius:14px;
    padding:14px 16px;
    margin:10px 0;
    line-height:1.65;
    font-size:16px;
}
.box-warn{
    background:#fff7ed;
    border:2px solid #fed7aa;
    border-left:8px solid #f97316;
    border-radius:14px;
    padding:14px 16px;
    margin:10px 0;
    line-height:1.65;
    font-size:16px;
}
.box-good{
    background:#f0fdf4;
    border:2px solid #bbf7d0;
    border-left:8px solid #16a34a;
    border-radius:14px;
    padding:14px 16px;
    margin:10px 0;
    line-height:1.65;
    font-size:16px;
}
.box-bad{
    background:#fef2f2;
    border:2px solid #fecaca;
    border-left:8px solid #dc2626;
    border-radius:14px;
    padding:14px 16px;
    margin:10px 0;
    line-height:1.65;
    font-size:16px;
}
.board-card{
    display:inline-block;
    background:#ffffff;
    border:2px solid #cbd5e1;
    border-radius:16px;
    box-shadow:0 4px 14px rgba(15,23,42,0.08);
    padding:12px;
    margin:8px;
    vertical-align:top;
}
.board-name{
    text-align:center;
    font-size:18px;
    font-weight:800;
    margin-bottom:4px;
}
.board-score{
    text-align:center;
    font-size:14px;
    color:#334155;
    margin-bottom:8px;
    font-weight:700;
}
.grid3{
    border-collapse:collapse;
    margin:auto;
}
.grid3 td{
    width:58px;
    height:58px;
    border:2px solid #334155;
    text-align:center;
    font-size:27px;
    font-weight:900;
    background:#f8fafc;
}
.grid3 td.blank{
    background:#e2e8f0;
    color:#94a3b8;
}
.step-table{
    width:100%;
    border-collapse:collapse;
    margin:12px 0;
    background:#ffffff;
    table-layout:fixed;
    font-size:14px;
}
.step-table th{
    background:#e0f2fe;
    color:#0f172a;
    border:1px solid #94a3b8;
    padding:9px;
    text-align:center;
    font-weight:900;
}
.step-table td{
    border:1px solid #cbd5e1;
    padding:8px;
    vertical-align:top;
    word-wrap:break-word;
}
.step-table tr:nth-child(even) td{
    background:#f8fafc;
}
.matrix-text{
    white-space:pre-line;
    font-family:Consolas, monospace;
    font-size:15px;
    line-height:1.4;
}
.path-line{
    display:flex;
    flex-wrap:wrap;
    align-items:flex-start;
}
.arrow{
    font-size:28px;
    font-weight:900;
    color:#1e293b;
    margin:80px 2px 0 2px;
}
.move-label{
    display:block;
    text-align:center;
    font-size:13px;
    font-weight:800;
    color:#2563eb;
}
.small-code{
    font-family:Consolas, monospace;
    background:#f1f5f9;
    padding:2px 6px;
    border-radius:6px;
}
</style>
"""


def show_html(raw: str) -> None:
    if NOTEBOOK_MODE:
        display(HTML(raw))
    else:
        print(raw)


def load_theme() -> None:
    show_html(LIGHT_THEME)


# ============================================================
# 2. MODEL BÀI TOÁN 8 PUZZLE
# ============================================================

@dataclass(frozen=True)
class PuzzleProblem:
    start: Board
    goal: Board
    move_order: str = "LRUD"
    heuristic_name: str = "misplaced"

    def h(self, board: Board) -> int:
        if self.heuristic_name == "manhattan":
            return manhattan_distance(board, self.goal)
        return misplaced_count(board, self.goal)

    def expand(self, board: Board) -> List[Tuple[Move, Board, int]]:
        """Trả về danh sách neighbor theo đúng thứ tự L R U D."""
        result: List[Tuple[Move, Board, int]] = []
        for mv in self.move_order:
            new_board = slide_blank(board, mv)
            if new_board is not None:
                result.append((mv, new_board, self.h(new_board)))
        return result

    def goal_test(self, board: Board) -> bool:
        return board == self.goal


@dataclass
class StepRecord:
    restart: int
    step: int
    node: str
    board: Board
    h_node: int
    frontier: str
    chosen: str
    reached: str
    note: str


@dataclass
class SearchReport:
    algorithm: str
    status: str
    message: str
    path: List[Board]
    moves: List[Move]
    trace: List[StepRecord] = field(default_factory=list)


class NameBook:
    """Đặt tên N0, N1, N2... cho các trạng thái để bảng dễ đọc."""

    def __init__(self) -> None:
        self._names: Dict[Board, str] = {}

    def name(self, board: Board) -> str:
        if board not in self._names:
            self._names[board] = f"N{len(self._names)}"
        return self._names[board]

    def reached_text(self, boards: Iterable[Board], limit: int = 10) -> str:
        names = [self.name(b) for b in boards]
        if len(names) <= limit:
            return "{" + ", ".join(names) + "}"
        head = ", ".join(names[:limit])
        return "{" + head + f", ... +{len(names) - limit}" + "}"


# ============================================================
# 3. HÀM CƠ BẢN
# ============================================================


def parse_board(text: str) -> Board:
    """Nhập được cả dạng nhiều dòng hoặc có dấu /."""
    cleaned = text.replace("/", " ").replace(",", " ")
    values = [int(x) for x in cleaned.split()]

    if len(values) != 9:
        raise ValueError("Bạn phải nhập đúng 9 số.")
    if sorted(values) != list(range(9)):
        raise ValueError("Bảng phải có đủ các số 0,1,2,3,4,5,6,7,8 và không trùng.")

    return tuple(values)



def board_to_lines(board: Board) -> str:
    return "\n".join(
        " ".join(str(x) for x in board[i:i + 3])
        for i in range(0, 9, 3)
    )



def misplaced_count(board: Board, goal: Board) -> int:
    """h(n) = số ô sai vị trí, không tính ô 0."""
    wrong = 0
    for i, value in enumerate(board):
        if value != 0 and value != goal[i]:
            wrong += 1
    return wrong



def manhattan_distance(board: Board, goal: Board) -> int:
    """Tổng khoảng cách Manhattan, không tính ô 0."""
    goal_pos = {value: index for index, value in enumerate(goal)}
    total = 0
    for index, value in enumerate(board):
        if value == 0:
            continue
        r1, c1 = divmod(index, 3)
        r2, c2 = divmod(goal_pos[value], 3)
        total += abs(r1 - r2) + abs(c1 - c2)
    return total



def count_inversions(board: Board) -> int:
    arr = [x for x in board if x != 0]
    inv = 0
    for i in range(len(arr)):
        for j in range(i + 1, len(arr)):
            if arr[i] > arr[j]:
                inv += 1
    return inv



def same_parity(start: Board, goal: Board) -> bool:
    return count_inversions(start) % 2 == count_inversions(goal) % 2



def slide_blank(board: Board, move: Move) -> Optional[Board]:
    zero = board.index(0)
    r, c = divmod(zero, 3)
    target: Optional[int] = None

    if move == "L" and c > 0:
        target = zero - 1
    elif move == "R" and c < 2:
        target = zero + 1
    elif move == "U" and r > 0:
        target = zero - 3
    elif move == "D" and r < 2:
        target = zero + 3

    if target is None:
        return None

    new_board = list(board)
    new_board[zero], new_board[target] = new_board[target], new_board[zero]
    return tuple(new_board)



def make_random_solvable_board(goal: Board, steps: int, rng: random.Random) -> Board:
    """Tạo state ngẫu nhiên bằng cách đi ngẫu nhiên từ goal nên luôn giải được."""
    board = goal
    last_move: Optional[Move] = None
    opposite = {"L": "R", "R": "L", "U": "D", "D": "U"}

    for _ in range(steps):
        options: List[Tuple[Move, Board]] = []
        for mv in "LRUD":
            if last_move is not None and mv == opposite[last_move]:
                continue
            nxt = slide_blank(board, mv)
            if nxt is not None:
                options.append((mv, nxt))

        if not options:
            for mv in "LRUD":
                nxt = slide_blank(board, mv)
                if nxt is not None:
                    options.append((mv, nxt))

        last_move, board = rng.choice(options)

    return board


# ============================================================
# 4. FORMAT HIỂN THỊ
# ============================================================


def board_card(problem: PuzzleProblem, board: Board, title: str) -> str:
    cells = ""
    for r in range(3):
        cells += "<tr>"
        for c in range(3):
            value = board[r * 3 + c]
            cls = "blank" if value == 0 else ""
            shown = "&nbsp;" if value == 0 else str(value)
            cells += f"<td class='{cls}'>{shown}</td>"
        cells += "</tr>"

    return f"""
    <div class='board-card'>
        <div class='board-name'>{html.escape(title)}</div>
        <div class='board-score'>h = {problem.h(board)}</div>
        <table class='grid3'>{cells}</table>
    </div>
    """



def frontier_text(problem: PuzzleProblem, items: Sequence[Tuple[Move, Board, int]], names: NameBook) -> str:
    if not items:
        return "[]"
    parts = []
    for mv, board, hval in items:
        parts.append(f"({mv}→{names.name(board)}, h={hval})")
    return "[" + ", ".join(parts) + "]"



def chosen_text(chosen: Optional[Tuple[Move, Board, int]], names: NameBook) -> str:
    if chosen is None:
        return "Không chọn"
    mv, board, hval = chosen
    return f"{mv} → {names.name(board)}, h={hval}"



def add_step(
    trace: List[StepRecord],
    problem: PuzzleProblem,
    names: NameBook,
    restart: int,
    step: int,
    board: Board,
    frontier: Sequence[Tuple[Move, Board, int]],
    chosen: Optional[Tuple[Move, Board, int]],
    reached: Sequence[Board],
    note: str,
) -> None:
    trace.append(
        StepRecord(
            restart=restart,
            step=step,
            node=names.name(board),
            board=board,
            h_node=problem.h(board),
            frontier=frontier_text(problem, frontier, names),
            chosen=chosen_text(chosen, names),
            reached=names.reached_text(reached),
            note=note,
        )
    )



def trace_to_html(trace: Sequence[StepRecord]) -> str:
    if not trace:
        return "<div class='box-note'>Không có bước nào để hiển thị.</div>"

    headers = [
        "Restart", "Step", "Node", "Ma trận hiện tại", "h(Node)",
        "Frontier / Neighbor", "Node chọn", "Reached", "Ghi chú"
    ]

    rows = ""
    for item in trace:
        matrix = html.escape(board_to_lines(item.board))
        rows += f"""
        <tr>
            <td>{item.restart}</td>
            <td>{item.step}</td>
            <td><b>{item.node}</b></td>
            <td><div class='matrix-text'>{matrix}</div></td>
            <td>{item.h_node}</td>
            <td>{html.escape(item.frontier)}</td>
            <td>{html.escape(item.chosen)}</td>
            <td>{html.escape(item.reached)}</td>
            <td>{html.escape(item.note)}</td>
        </tr>
        """

    head = "".join(f"<th>{h}</th>" for h in headers)
    return f"<table class='step-table'><tr>{head}</tr>{rows}</table>"



def path_to_html(problem: PuzzleProblem, path: Sequence[Board], moves: Sequence[Move]) -> str:
    if not path:
        return ""

    content = "<div class='path-line'>"
    for i, board in enumerate(path):
        content += board_card(problem, board, f"Bước {i}")
        if i < len(path) - 1:
            mv = moves[i] if i < len(moves) else "?"
            content += f"<div class='arrow'>→<span class='move-label'>{mv}</span></div>"
    content += "</div>"
    return content



def show_report(problem: PuzzleProblem, report: SearchReport, show_trace: bool = True) -> None:
    load_theme()

    if report.status == "success":
        box = "box-good"
    elif report.status == "stuck":
        box = "box-warn"
    else:
        box = "box-bad"

    final_h = problem.h(report.path[-1]) if report.path else "?"
    show_html(f"""
    <div class='eight-wrap'>
        <div class='eight-title'>{html.escape(report.algorithm)}</div>
        <div class='{box}'>
            <b>Kết quả:</b> {html.escape(report.message)}<br>
            <b>Trạng thái:</b> {html.escape(report.status)}<br>
            <b>Số bước path:</b> {max(0, len(report.path) - 1)}<br>
            <b>h cuối:</b> {final_h}
        </div>
    </div>
    """)

    show_html("<div class='eight-title'>Start và Goal</div>")
    show_html(board_card(problem, problem.start, "Start") + board_card(problem, problem.goal, "Goal"))

    if show_trace:
        show_html("<div class='eight-title'>Bảng Node – Frontier – Reached</div>")
        show_html(trace_to_html(report.trace))

    show_html("<div class='eight-title'>Đường đi</div>")
    show_html(path_to_html(problem, report.path, report.moves))


# ============================================================
# 5. BỘ MÁY CHUNG CHO 3 KIỂU LEO ĐỒI
# ============================================================

Chooser = Callable[[PuzzleProblem, Board, List[Tuple[Move, Board, int]], List[Board], random.Random], Optional[Tuple[Move, Board, int]]]



def local_search_core(
    problem: PuzzleProblem,
    algorithm_name: str,
    chooser: Chooser,
    max_steps: int,
    seed: int,
    restart_id: int = 0,
    forced_start: Optional[Board] = None,
) -> SearchReport:
    rng = random.Random(seed)
    names = NameBook()
    current = forced_start if forced_start is not None else problem.start
    path: List[Board] = [current]
    moves: List[Move] = []
    reached: List[Board] = [current]
    reached_set = {current}
    trace: List[StepRecord] = []

    for step in range(max_steps + 1):
        if problem.goal_test(current):
            add_step(
                trace, problem, names, restart_id, step, current, [], None, reached,
                "Đã tới goal nên dừng."
            )
            return SearchReport(
                algorithm=algorithm_name,
                status="success",
                message="Tìm thấy goal.",
                path=path,
                moves=moves,
                trace=trace,
            )

        frontier = problem.expand(current)
        frontier = [item for item in frontier if item[1] not in reached_set]
        chosen = chooser(problem, current, frontier, reached, rng)

        if chosen is None:
            add_step(
                trace, problem, names, restart_id, step, current, frontier, None, reached,
                "Không chọn được node tốt hơn → bị kẹt tại local optimum/plateau."
            )
            return SearchReport(
                algorithm=algorithm_name,
                status="stuck",
                message="Không tìm thấy goal vì bị kẹt tại cực trị cục bộ hoặc vùng bằng phẳng.",
                path=path,
                moves=moves,
                trace=trace,
            )

        mv, new_board, new_h = chosen
        add_step(
            trace, problem, names, restart_id, step, current, frontier, chosen, reached,
            f"Đi theo move {mv} vì h giảm từ {problem.h(current)} xuống {new_h}."
        )

        current = new_board
        path.append(current)
        moves.append(mv)
        reached.append(current)
        reached_set.add(current)

    return SearchReport(
        algorithm=algorithm_name,
        status="cutoff",
        message=f"Dừng vì vượt quá max_steps = {max_steps}.",
        path=path,
        moves=moves,
        trace=trace,
    )


# ============================================================
# 6. 4 THUẬT TOÁN LEO ĐỒI
# ============================================================


def choose_first_better(
    problem: PuzzleProblem,
    current: Board,
    frontier: List[Tuple[Move, Board, int]],
    reached: List[Board],
    rng: random.Random,
) -> Optional[Tuple[Move, Board, int]]:
    """Leo đồi đơn giản: gặp neighbor nào tốt hơn đầu tiên thì chọn ngay."""
    current_h = problem.h(current)
    for item in frontier:
        if item[2] < current_h:
            return item
    return None



def choose_best_better(
    problem: PuzzleProblem,
    current: Board,
    frontier: List[Tuple[Move, Board, int]],
    reached: List[Board],
    rng: random.Random,
) -> Optional[Tuple[Move, Board, int]]:
    """Leo đồi dốc nhất: xét hết frontier rồi chọn neighbor có h nhỏ nhất."""
    current_h = problem.h(current)
    if not frontier:
        return None

    best = min(frontier, key=lambda item: item[2])
    if best[2] < current_h:
        return best
    return None



def choose_random_better(
    problem: PuzzleProblem,
    current: Board,
    frontier: List[Tuple[Move, Board, int]],
    reached: List[Board],
    rng: random.Random,
) -> Optional[Tuple[Move, Board, int]]:
    """Leo đồi ngẫu nhiên: lọc các neighbor tốt hơn rồi bốc ngẫu nhiên 1 node."""
    current_h = problem.h(current)
    better = [item for item in frontier if item[2] < current_h]
    if not better:
        return None
    return rng.choice(better)



def simple_hill_climbing(problem: PuzzleProblem, max_steps: int = 100, seed: int = 42) -> SearchReport:
    return local_search_core(
        problem=problem,
        algorithm_name="1. Leo đồi đơn giản / First-choice Hill Climbing",
        chooser=choose_first_better,
        max_steps=max_steps,
        seed=seed,
    )



def steepest_hill_climbing(problem: PuzzleProblem, max_steps: int = 100, seed: int = 42) -> SearchReport:
    return local_search_core(
        problem=problem,
        algorithm_name="2. Leo đồi dốc nhất / Steepest-ascent Hill Climbing",
        chooser=choose_best_better,
        max_steps=max_steps,
        seed=seed,
    )



def stochastic_hill_climbing(problem: PuzzleProblem, max_steps: int = 100, seed: int = 42) -> SearchReport:
    return local_search_core(
        problem=problem,
        algorithm_name="3. Leo đồi ngẫu nhiên / Stochastic Hill Climbing",
        chooser=choose_random_better,
        max_steps=max_steps,
        seed=seed,
    )



def random_restart_hill_climbing(
    problem: PuzzleProblem,
    max_steps: int = 100,
    seed: int = 42,
    restarts: int = 10,
    random_walk_steps: int = 25,
) -> SearchReport:
    """
    Chạy nhiều lần leo đồi dốc nhất.
    Restart 0 dùng Start ban đầu.
    Các restart sau tạo state ngẫu nhiên bằng cách đi random từ Goal.
    """
    master_rng = random.Random(seed)
    all_trace: List[StepRecord] = []
    best_path: List[Board] = [problem.start]
    best_moves: List[Move] = []
    best_h = problem.h(problem.start)

    for rid in range(restarts + 1):
        if rid == 0:
            candidate_start = problem.start
        else:
            candidate_start = make_random_solvable_board(
                goal=problem.goal,
                steps=random_walk_steps,
                rng=master_rng,
            )

        attempt = local_search_core(
            problem=problem,
            algorithm_name="4. Leo đồi khởi động lại ngẫu nhiên / Random-restart Hill Climbing",
            chooser=choose_best_better,
            max_steps=max_steps,
            seed=master_rng.randint(1, 10**9),
            restart_id=rid,
            forced_start=candidate_start,
        )

        all_trace.extend(attempt.trace)
        last_h = problem.h(attempt.path[-1])

        if last_h < best_h:
            best_h = last_h
            best_path = attempt.path
            best_moves = attempt.moves

        if attempt.status == "success":
            return SearchReport(
                algorithm="4. Leo đồi khởi động lại ngẫu nhiên / Random-restart Hill Climbing",
                status="success",
                message=f"Tìm thấy goal ở restart {rid}.",
                path=attempt.path,
                moves=attempt.moves,
                trace=all_trace,
            )

    return SearchReport(
        algorithm="4. Leo đồi khởi động lại ngẫu nhiên / Random-restart Hill Climbing",
        status="stuck",
        message=f"Chưa tìm thấy goal sau {restarts} lần restart. Path tốt nhất có h = {best_h}.",
        path=best_path,
        moves=best_moves,
        trace=all_trace,
    )


ALGORITHM_MAP = {
    "Leo đồi đơn giản": simple_hill_climbing,
    "Leo đồi dốc nhất": steepest_hill_climbing,
    "Leo đồi ngẫu nhiên": stochastic_hill_climbing,
    "Leo đồi khởi động lại ngẫu nhiên": random_restart_hill_climbing,
}


# ============================================================
# 7. HÀM CHẠY VÀ SO SÁNH
# ============================================================


def build_problem(
    start_text: str,
    goal_text: str,
    move_order: str = "LRUD",
    heuristic_name: str = "misplaced",
) -> PuzzleProblem:
    order = "".join(ch for ch in move_order.upper() if ch in "LRUD")
    if not order:
        order = "LRUD"

    return PuzzleProblem(
        start=parse_board(start_text),
        goal=parse_board(goal_text),
        move_order=order,
        heuristic_name=heuristic_name,
    )



def run_algorithm(
    algorithm_name: str,
    start_text: str,
    goal_text: str,
    move_order: str = "LRUD",
    heuristic_name: str = "misplaced",
    max_steps: int = 100,
    seed: int = 42,
    restarts: int = 10,
    random_walk_steps: int = 25,
    show_trace: bool = True,
) -> SearchReport:
    if NOTEBOOK_MODE:
        clear_output(wait=True)

    problem = build_problem(start_text, goal_text, move_order, heuristic_name)
    load_theme()

    heuristic_label = "số ô sai vị trí" if heuristic_name == "misplaced" else "Manhattan"
    show_html(f"""
    <div class='box-note'>
        <b>Ý nghĩa:</b> Ta xem mỗi trạng thái 8-puzzle là một node.<br>
        <b>Frontier:</b> các trạng thái sinh ra khi di chuyển ô trống theo thứ tự
        <span class='small-code'>{html.escape(problem.move_order)}</span>.<br>
        <b>Reached:</b> các node đã đi qua trong lần chạy hiện tại.<br>
        <b>Heuristic đang dùng:</b> h(n) = {heuristic_label}.<br>
        <b>Mục tiêu:</b> làm h(n) giảm dần về 0.
    </div>
    """)

    if not same_parity(problem.start, problem.goal):
        show_html("""
        <div class='box-warn'>
            <b>Cảnh báo:</b> Start và Goal khác parity nghịch thế. Với 8-puzzle 3x3,
            trường hợp này thường không giải được bằng chuỗi di chuyển hợp lệ.
        </div>
        """)

    if algorithm_name == "Leo đồi khởi động lại ngẫu nhiên":
        report = random_restart_hill_climbing(
            problem=problem,
            max_steps=max_steps,
            seed=seed,
            restarts=restarts,
            random_walk_steps=random_walk_steps,
        )
    else:
        fn = ALGORITHM_MAP[algorithm_name]
        report = fn(problem, max_steps=max_steps, seed=seed)

    show_report(problem, report, show_trace=show_trace)
    return report



def compare_all_algorithms(
    start_text: str,
    goal_text: str,
    move_order: str = "LRUD",
    heuristic_name: str = "misplaced",
    max_steps: int = 100,
    seed: int = 42,
    restarts: int = 10,
    random_walk_steps: int = 25,
) -> List[SearchReport]:
    if NOTEBOOK_MODE:
        clear_output(wait=True)

    problem = build_problem(start_text, goal_text, move_order, heuristic_name)
    load_theme()
    reports: List[SearchReport] = []

    reports.append(simple_hill_climbing(problem, max_steps=max_steps, seed=seed))
    reports.append(steepest_hill_climbing(problem, max_steps=max_steps, seed=seed))
    reports.append(stochastic_hill_climbing(problem, max_steps=max_steps, seed=seed))
    reports.append(random_restart_hill_climbing(
        problem,
        max_steps=max_steps,
        seed=seed,
        restarts=restarts,
        random_walk_steps=random_walk_steps,
    ))

    show_html("<div class='eight-title'>So sánh đủ 4 thuật toán</div>")
    show_html(board_card(problem, problem.start, "Start") + board_card(problem, problem.goal, "Goal"))

    rows = ""
    for report in reports:
        final_h = problem.h(report.path[-1])
        rows += f"""
        <tr>
            <td>{html.escape(report.algorithm)}</td>
            <td>{html.escape(report.status)}</td>
            <td>{max(0, len(report.path) - 1)}</td>
            <td>{final_h}</td>
            <td>{html.escape(report.message)}</td>
        </tr>
        """

    show_html(f"""
    <table class='step-table'>
        <tr>
            <th>Thuật toán</th>
            <th>Trạng thái</th>
            <th>Số bước path</th>
            <th>h cuối</th>
            <th>Nhận xét</th>
        </tr>
        {rows}
    </table>
    """)

    return reports


# ============================================================
# 8. GIAO DIỆN JUPYTER / COLAB
# ============================================================


def create_app() -> None:
    load_theme()

    if not WIDGET_READY:
        show_html("""
        <div class='box-warn'>
            Máy hiện chưa có <b>ipywidgets</b>. Bạn có thể chạy thủ công bằng hàm
            <span class='small-code'>run_algorithm(...)</span> hoặc cài:
            <pre>pip install ipywidgets</pre>
        </div>
        """)
        return

    start_box = widgets.Textarea(
        value="2 8 3\n1 6 4\n7 0 5",
        description="Start",
        layout=widgets.Layout(width="360px", height="110px"),
    )

    goal_box = widgets.Textarea(
        value="1 2 3\n8 0 4\n7 6 5",
        description="Goal",
        layout=widgets.Layout(width="360px", height="110px"),
    )

    algo_box = widgets.Dropdown(
        options=list(ALGORITHM_MAP.keys()),
        value="Leo đồi đơn giản",
        description="Thuật toán",
        layout=widgets.Layout(width="440px"),
    )

    heuristic_box = widgets.Dropdown(
        options=[
            ("h = số ô sai vị trí", "misplaced"),
            ("h = Manhattan", "manhattan"),
        ],
        value="misplaced",
        description="Heuristic",
        layout=widgets.Layout(width="300px"),
    )

    order_box = widgets.Text(
        value="LRUD",
        description="Thứ tự",
        layout=widgets.Layout(width="180px"),
    )

    max_step_box = widgets.IntSlider(
        value=100,
        min=5,
        max=500,
        step=5,
        description="Max step",
        layout=widgets.Layout(width="420px"),
    )

    seed_box = widgets.IntText(
        value=42,
        description="Seed",
        layout=widgets.Layout(width="170px"),
    )

    restart_box = widgets.IntSlider(
        value=10,
        min=1,
        max=100,
        step=1,
        description="Restart",
        layout=widgets.Layout(width="420px"),
    )

    random_walk_box = widgets.IntSlider(
        value=25,
        min=5,
        max=100,
        step=5,
        description="Random walk",
        layout=widgets.Layout(width="420px"),
    )

    trace_check = widgets.Checkbox(
        value=True,
        description="Hiện bảng Node - Frontier - Reached",
    )

    run_btn = widgets.Button(
        description="Chạy thuật toán đang chọn",
        icon="play",
        button_style="success",
        layout=widgets.Layout(width="260px"),
    )

    compare_btn = widgets.Button(
        description="So sánh đủ 4 thuật toán",
        icon="bar-chart",
        button_style="info",
        layout=widgets.Layout(width="260px"),
    )

    out = widgets.Output(layout=widgets.Layout(border="1px solid #cbd5e1", padding="10px"))

    def on_run_clicked(_btn) -> None:
        with out:
            run_algorithm(
                algorithm_name=algo_box.value,
                start_text=start_box.value,
                goal_text=goal_box.value,
                move_order=order_box.value,
                heuristic_name=heuristic_box.value,
                max_steps=max_step_box.value,
                seed=seed_box.value,
                restarts=restart_box.value,
                random_walk_steps=random_walk_box.value,
                show_trace=trace_check.value,
            )

    def on_compare_clicked(_btn) -> None:
        with out:
            compare_all_algorithms(
                start_text=start_box.value,
                goal_text=goal_box.value,
                move_order=order_box.value,
                heuristic_name=heuristic_box.value,
                max_steps=max_step_box.value,
                seed=seed_box.value,
                restarts=restart_box.value,
                random_walk_steps=random_walk_box.value,
            )

    run_btn.on_click(on_run_clicked)
    compare_btn.on_click(on_compare_clicked)

    intro = widgets.HTML("""
    <div class='eight-wrap'>
        <div class='eight-title'>8 Puzzle - Hill Climbing Family</div>
        <div class='eight-subtitle'>
            Bản code mới: tách Problem, SearchReport, StepRecord. Có đủ 4 thuật toán và bảng Node - Frontier - Reached.
        </div>
    </div>
    """)

    controls = widgets.VBox([
        intro,
        widgets.HBox([start_box, goal_box]),
        widgets.HBox([algo_box, heuristic_box]),
        widgets.HBox([order_box, seed_box]),
        max_step_box,
        restart_box,
        random_walk_box,
        trace_check,
        widgets.HBox([run_btn, compare_btn]),
        out,
    ])

    display(controls)


# ============================================================
# 9. CHẠY APP
# ============================================================

# Khi copy vào Jupyter/Colab, chỉ cần chạy cell này là hiện giao diện.
create_app()


# ============================================================
# 10. CÁCH CHẠY THỦ CÔNG NẾU KHÔNG MUỐN DÙNG GIAO DIỆN
# ============================================================
# Ví dụ:
# run_algorithm(
#     algorithm_name="Leo đồi dốc nhất",
#     start_text="2 8 3 / 1 6 4 / 7 0 5",
#     goal_text="1 2 3 / 8 0 4 / 7 6 5",
#     move_order="LRUD",
#     heuristic_name="misplaced",
#     max_steps=100,
#     seed=42,
#     restarts=10,
# )
#
# compare_all_algorithms(
#     start_text="2 8 3 / 1 6 4 / 7 0 5",
#     goal_text="1 2 3 / 8 0 4 / 7 6 5",
# )