# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import heapq
import random
import time
import asyncio
import html
import ipywidgets as widgets
from IPython.display import display

# =========================
# 8 PUZZLE - UCS NOTEBOOK VERSION
# Không dùng Tkinter
# Chạy được trong Jupyter / Colab
# =========================

GOAL = (
    1, 2, 3,
    4, 5, 6,
    7, 8, 0
)

MOVE_ORDER = [
    ("Up", -1, 0),
    ("Down", 1, 0),
    ("Left", 0, -1),
    ("Right", 0, 1)
]


def state_to_text(state):
    return (
        f"{state[0]} {state[1]} {state[2]}<br>"
        f"{state[3]} {state[4]} {state[5]}<br>"
        f"{state[6]} {state[7]} {state[8]}"
    )


def state_to_one_line(state):
    return (
        f"{state[0]}{state[1]}{state[2]}/"
        f"{state[3]}{state[4]}{state[5]}/"
        f"{state[6]}{state[7]}{state[8]}"
    )


def is_solvable(state):
    arr = [x for x in state if x != 0]
    inv = 0

    for i in range(len(arr)):
        for j in range(i + 1, len(arr)):
            if arr[i] > arr[j]:
                inv += 1

    return inv % 2 == 0


def get_neighbors(state):
    zero_index = state.index(0)
    zr, zc = zero_index // 3, zero_index % 3

    neighbors = []

    for action, dr, dc in MOVE_ORDER:
        nr = zr + dr
        nc = zc + dc

        if 0 <= nr < 3 and 0 <= nc < 3:
            new_index = nr * 3 + nc

            tile_moved = state[new_index]
            step_cost = tile_moved

            new_state = list(state)
            new_state[zero_index], new_state[new_index] = (
                new_state[new_index],
                new_state[zero_index]
            )

            neighbors.append(
                (
                    tuple(new_state),
                    action,
                    tile_moved,
                    step_cost
                )
            )

    return neighbors


def reconstruct_path(parent, goal_state):
    path = []
    actions = []
    moved_tiles = []
    costs = []

    current = goal_state

    while current is not None:
        path.append(current)

        info = parent[current]

        if info is None:
            break

        prev_state, action, tile_moved, step_cost = info

        actions.append(action)
        moved_tiles.append(tile_moved)
        costs.append(step_cost)

        current = prev_state

    path.reverse()
    actions.reverse()
    moved_tiles.reverse()
    costs.reverse()

    return path, actions, moved_tiles, costs


def frontier_snapshot(frontier, best_cost, limit=5):
    valid_items = []

    for g, counter, state in frontier:
        if best_cost.get(state) == g:
            valid_items.append((g, counter, state))

    valid_items.sort(key=lambda x: (x[0], x[1]))

    show = []

    for g, _, state in valid_items[:limit]:
        show.append(f"{state_to_one_line(state)}(g={g})")

    if len(valid_items) > limit:
        show.append("...")

    return " | ".join(show)


def uniform_cost_search(start, max_nodes=100000):
    frontier = []
    counter = 0

    heapq.heappush(frontier, (0, counter, start))

    best_cost = {
        start: 0
    }

    parent = {
        start: None
    }

    log = []
    expanded = 0

    while frontier and expanded < max_nodes:
        g, _, current = heapq.heappop(frontier)

        if g != best_cost.get(current):
            continue

        expanded += 1

        if current == GOAL:
            path, actions, moved_tiles, costs = reconstruct_path(parent, current)

            log.append({
                "step": expanded,
                "node": state_to_one_line(current),
                "g": g,
                "frontier": frontier_snapshot(frontier, best_cost),
                "reached": len(best_cost),
                "note": "GOAL"
            })

            return {
                "found": True,
                "path": path,
                "actions": actions,
                "moved_tiles": moved_tiles,
                "costs": costs,
                "total_cost": g,
                "expanded": expanded,
                "log": log
            }

        for child, action, tile_moved, step_cost in get_neighbors(current):
            new_g = g + step_cost

            if child not in best_cost or new_g < best_cost[child]:
                best_cost[child] = new_g
                parent[child] = (current, action, tile_moved, step_cost)

                counter += 1
                heapq.heappush(frontier, (new_g, counter, child))

        log.append({
            "step": expanded,
            "node": state_to_one_line(current),
            "g": g,
            "frontier": frontier_snapshot(frontier, best_cost),
            "reached": len(best_cost),
            "note": ""
        })

    return {
        "found": False,
        "path": [],
        "actions": [],
        "moved_tiles": [],
        "costs": [],
        "total_cost": None,
        "expanded": expanded,
        "log": log
    }


class EightPuzzleUCSNotebook:
    def __init__(self):
        self.start_state = (
            1, 2, 3,
            4, 0, 6,
            7, 5, 8
        )

        self.state = self.start_state

        self.solution = None
        self.solution_index = 0

        self.manual_moves = 0
        self.manual_cost = 0

        self.auto_running = False

        self.tile_buttons = []
        self.goal_buttons = []

        self.max_nodes_input = widgets.IntText(
            value=100000,
            description="Max nodes:",
            layout=widgets.Layout(width="180px")
        )

        self.random_steps_input = widgets.IntText(
            value=20,
            description="Random:",
            layout=widgets.Layout(width="180px")
        )

        self.btn_random = widgets.Button(description="Random", button_style="info")
        self.btn_reset = widgets.Button(description="Reset")
        self.btn_solve = widgets.Button(description="Solve UCS", button_style="success")
        self.btn_next = widgets.Button(description="Next ▶", button_style="warning")
        self.btn_auto = widgets.Button(description="Auto Run")
        self.btn_stop = widgets.Button(description="Stop", button_style="danger")

        self.status = widgets.HTML()
        self.log_html = widgets.HTML()

        self.create_ui()
        self.update_board()
        self.update_status("Sẵn sàng. Thuật toán đang dùng: UCS.")

    def create_board_buttons(self):
        self.tile_buttons = []

        for i in range(9):
            btn = widgets.Button(
                description="",
                layout=widgets.Layout(width="65px", height="65px")
            )

            btn.style.font_weight = "bold"
            btn.on_click(lambda b, idx=i: self.click_tile(idx))

            self.tile_buttons.append(btn)

        board = widgets.GridBox(
            self.tile_buttons,
            layout=widgets.Layout(
                grid_template_columns="repeat(3, 65px)",
                grid_gap="5px"
            )
        )

        return board

    def create_goal_buttons(self):
        self.goal_buttons = []

        for i, value in enumerate(GOAL):
            btn = widgets.Button(
                description="" if value == 0 else str(value),
                disabled=True,
                layout=widgets.Layout(width="45px", height="45px")
            )

            btn.style.button_color = "#e2e8f0"
            self.goal_buttons.append(btn)

        goal_board = widgets.GridBox(
            self.goal_buttons,
            layout=widgets.Layout(
                grid_template_columns="repeat(3, 45px)",
                grid_gap="3px"
            )
        )

        return goal_board

    def create_ui(self):
        board = self.create_board_buttons()
        goal_board = self.create_goal_buttons()

        self.btn_random.on_click(self.randomize)
        self.btn_reset.on_click(self.reset_game)
        self.btn_solve.on_click(self.solve_ucs)
        self.btn_next.on_click(self.next_step)
        self.btn_auto.on_click(self.auto_run)
        self.btn_stop.on_click(self.stop_auto)

        controls = widgets.VBox([
            widgets.HTML("<h3>Điều khiển</h3>"),
            widgets.HTML(
                """
                <b>Thuật toán:</b> UCS<br>
                <b>Cost:</b> số bị swap với ô 0<br>
                Ví dụ: 0 swap với 5 thì cost +5
                """
            ),
            self.max_nodes_input,
            self.random_steps_input,
            widgets.HBox([self.btn_random, self.btn_reset]),
            widgets.HBox([self.btn_solve, self.btn_next]),
            widgets.HBox([self.btn_auto, self.btn_stop]),
            self.status
        ])

        left = widgets.VBox([
            widgets.HTML("<h2>8 Puzzle - UCS</h2>"),
            board,
            widgets.HTML("<h4>GOAL</h4>"),
            goal_board
        ])

        right = widgets.VBox([
            widgets.HTML("<h3>Bảng chạy UCS: Node / Frontier / Reached / Cost</h3>"),
            self.log_html
        ])

        app = widgets.HBox([
            left,
            controls,
            right
        ], layout=widgets.Layout(gap="25px"))

        display(app)

    def update_board(self):
        for i, value in enumerate(self.state):
            btn = self.tile_buttons[i]

            if value == 0:
                btn.description = ""
                btn.style.button_color = "#cbd5e1"
            else:
                btn.description = str(value)
                btn.style.button_color = "#f8fafc"

        if self.state == GOAL:
            for btn in self.tile_buttons:
                btn.style.button_color = "#bbf7d0"

    def update_status(self, text):
        self.status.value = f"""
        <div style="
            border:1px solid #ddd;
            padding:10px;
            margin-top:10px;
            width:310px;
            background:#f8fafc;
            white-space:pre-wrap;
            font-family:monospace;
        ">{html.escape(text)}</div>
        """

    def click_tile(self, idx):
        zero = self.state.index(0)

        zr, zc = zero // 3, zero % 3
        r, c = idx // 3, idx % 3

        if abs(zr - r) + abs(zc - c) != 1:
            return

        tile_moved = self.state[idx]
        step_cost = tile_moved

        new_state = list(self.state)
        new_state[zero], new_state[idx] = new_state[idx], new_state[zero]

        self.state = tuple(new_state)

        self.manual_moves += 1
        self.manual_cost += step_cost

        self.solution = None
        self.solution_index = 0

        self.update_board()
        self.clear_log()

        if self.state == GOAL:
            self.update_status(
                f"Bạn đã hoàn thành!\n"
                f"Số bước: {self.manual_moves}\n"
                f"Tổng cost: {self.manual_cost}"
            )
        else:
            self.update_status(
                f"Bạn vừa swap ô 0 với ô {tile_moved}\n"
                f"Step cost = {step_cost}\n"
                f"Manual moves = {self.manual_moves}\n"
                f"Manual cost = {self.manual_cost}"
            )

    def randomize(self, b=None):
        steps = self.random_steps_input.value

        state = GOAL
        previous = None

        for _ in range(max(1, steps)):
            candidates = get_neighbors(state)

            if previous is not None:
                filtered = [item for item in candidates if item[0] != previous]
                candidates = filtered or candidates

            new_state, _, _, _ = random.choice(candidates)

            previous = state
            state = new_state

        self.state = state
        self.start_state = state

        self.manual_moves = 0
        self.manual_cost = 0

        self.solution = None
        self.solution_index = 0
        self.auto_running = False

        self.update_board()
        self.clear_log()

        self.update_status(
            "Đã random trạng thái mới.\n"
            "Trạng thái này chắc chắn giải được."
        )

    def reset_game(self, b=None):
        self.state = self.start_state

        self.manual_moves = 0
        self.manual_cost = 0

        self.solution = None
        self.solution_index = 0
        self.auto_running = False

        self.update_board()
        self.clear_log()

        self.update_status("Đã reset về trạng thái ban đầu.")

    def solve_ucs(self, b=None):
        if not is_solvable(self.state):
            self.update_status("Trạng thái này không giải được.")
            return

        start_time = time.time()

        result = uniform_cost_search(
            self.state,
            max_nodes=self.max_nodes_input.value
        )

        elapsed = time.time() - start_time

        self.solution = result
        self.solution_index = 0

        self.fill_log(result["log"])

        if result["found"]:
            lines = []

            current_g = 0

            for i, action in enumerate(result["actions"]):
                current_g += result["costs"][i]

                lines.append(
                    f"{i + 1}. {action}: swap 0 với {result['moved_tiles'][i]}, "
                    f"cost={result['costs'][i]}, g={current_g}"
                )

            self.update_status(
                f"UCS tìm thấy lời giải!\n"
                f"Số bước: {len(result['actions'])}\n"
                f"Tổng chi phí g: {result['total_cost']}\n"
                f"Số node đã xét: {result['expanded']}\n"
                f"Thời gian: {elapsed:.4f}s\n\n"
                f"Đường đi:\n" +
                "\n".join(lines)
            )
        else:
            self.update_status(
                f"UCS chưa tìm thấy lời giải.\n"
                f"Node đã xét: {result['expanded']}\n"
                f"Thời gian: {elapsed:.4f}s\n"
                f"Hãy tăng Max nodes."
            )

    def next_step(self, b=None):
        if not self.solution or not self.solution["found"]:
            self.update_status("Bạn hãy bấm Solve UCS trước.")
            return

        path = self.solution["path"]

        if self.solution_index >= len(path) - 1:
            self.update_status("Đã tới Goal rồi.")
            return

        self.solution_index += 1
        self.state = path[self.solution_index]

        self.update_board()

        action = self.solution["actions"][self.solution_index - 1]
        tile_moved = self.solution["moved_tiles"][self.solution_index - 1]
        step_cost = self.solution["costs"][self.solution_index - 1]
        current_g = sum(self.solution["costs"][:self.solution_index])

        self.update_status(
            f"Step {self.solution_index}/{len(path) - 1}\n"
            f"Action: {action}\n"
            f"Swap 0 với ô: {tile_moved}\n"
            f"Step cost: {step_cost}\n"
            f"g(n): {current_g}\n\n"
            f"Node hiện tại:\n"
            f"{state_to_one_line(self.state)}"
        )

    def auto_run(self, b=None):
        if not self.solution or not self.solution["found"]:
            self.update_status("Bạn hãy bấm Solve UCS trước.")
            return

        self.auto_running = True
        asyncio.create_task(self.auto_loop())

    async def auto_loop(self):
        while self.auto_running:
            if not self.solution:
                break

            if self.solution_index >= len(self.solution["path"]) - 1:
                break

            self.next_step()
            await asyncio.sleep(0.6)

        self.auto_running = False

    def stop_auto(self, b=None):
        self.auto_running = False
        self.update_status("Đã dừng Auto Run.")

    def clear_log(self):
        self.log_html.value = ""

    def fill_log(self, log):
        limit = 80
        rows = []

        for row in log[:limit]:
            rows.append(f"""
            <tr>
                <td>{row["step"]}</td>
                <td>{html.escape(row["node"])}</td>
                <td>{row["g"]}</td>
                <td style="text-align:left">{html.escape(row["frontier"])}</td>
                <td>{row["reached"]}</td>
                <td>{html.escape(row["note"])}</td>
            </tr>
            """)

        extra = ""

        if len(log) > limit:
            extra = f"""
            <p>Chỉ hiển thị {limit}/{len(log)} dòng đầu tiên.</p>
            """

        self.log_html.value = f"""
        <div style="max-height:520px; overflow:auto; width:720px;">
        <table border="1" cellspacing="0" cellpadding="5"
               style="border-collapse:collapse; font-size:12px;">
            <tr style="background:#e2e8f0;">
                <th>Step</th>
                <th>Node</th>
                <th>g(n)</th>
                <th>Frontier</th>
                <th>Reached</th>
                <th>Note</th>
            </tr>
            {''.join(rows)}
        </table>
        {extra}
        </div>
        """


app = EightPuzzleUCSNotebook()