# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#https://github.com/ngquyn2602/Bai_tap_tri_tue_nhan_tao_AI
import heapq
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

# =========================
# 1. BẢN ĐỒ MÁY HÚT BỤI
# =========================
# -1 là vật cản
# số dương là chi phí đi vào ô đó

grid = [
    [1, 1, 2, 1, 1],
    [1, -1, 3, -1, 1],
    [1, 1, 1, 2, 1],
    [2, -1, 1, 1, 1],
    [1, 1, 1, -1, 1]
]

start = (0, 0)

dirt_positions = {
    (0, 4),
    (2, 2),
    (4, 0),
    (4, 4)
}

ROWS = len(grid)
COLS = len(grid[0])

# Chi phí hút bụi tại một ô
SUCK_COST = 1


# =========================
# 2. HÀM HỖ TRỢ
# =========================

def is_valid(pos):
    r, c = pos
    return (
        0 <= r < ROWS and
        0 <= c < COLS and
        grid[r][c] != -1
    )


def get_neighbors(pos):
    r, c = pos

    directions = [
        ("Up", (-1, 0)),
        ("Down", (1, 0)),
        ("Left", (0, -1)),
        ("Right", (0, 1))
    ]

    neighbors = []

    for action, (dr, dc) in directions:
        new_pos = (r + dr, c + dc)

        if is_valid(new_pos):
            move_cost = grid[new_pos[0]][new_pos[1]]
            neighbors.append((action, new_pos, move_cost))

    return neighbors


def state_to_string(state):
    pos, remaining_dirt = state
    return f"Pos={pos}, Dirt={sorted(list(remaining_dirt))}"


# =========================
# 3. THUẬT TOÁN UCS
# =========================

def uniform_cost_search(start, dirt_positions):
    """
    State = (vị trí máy hút bụi, tập rác còn lại)
    Goal = không còn rác nào
    g(n) = tổng chi phí từ start đến trạng thái hiện tại
    """

    start_state = (start, frozenset(dirt_positions))

    # Frontier là priority queue
    # Mỗi phần tử: (cost, id, state, path, actions)
    frontier = []
    counter = 0

    heapq.heappush(frontier, (0, counter, start_state, [start], []))

    # Reached lưu chi phí nhỏ nhất đã biết tới mỗi state
    reached = {
        start_state: 0
    }

    log = []
    step = 0

    while frontier:
        cost, _, current_state, path, actions = heapq.heappop(frontier)

        current_pos, remaining_dirt = current_state

        # Nếu state này đã có đường tốt hơn trước đó thì bỏ qua
        if cost > reached[current_state]:
            continue

        step += 1

        log.append({
            "Step": step,
            "Node": state_to_string(current_state),
            "g": cost,
            "Frontier size": len(frontier),
            "Reached size": len(reached)
        })

        # Goal test
        if len(remaining_dirt) == 0:
            return {
                "cost": cost,
                "path": path,
                "actions": actions,
                "log": log,
                "reached": reached
            }

        # Nếu đang đứng trên ô có rác thì có thể hút
        if current_pos in remaining_dirt:
            new_remaining_dirt = set(remaining_dirt)
            new_remaining_dirt.remove(current_pos)

            new_state = (current_pos, frozenset(new_remaining_dirt))
            new_cost = cost + SUCK_COST

            if new_state not in reached or new_cost < reached[new_state]:
                reached[new_state] = new_cost
                counter += 1

                heapq.heappush(
                    frontier,
                    (
                        new_cost,
                        counter,
                        new_state,
                        path + [current_pos],
                        actions + [f"Suck dirt at {current_pos}"]
                    )
                )

        # Di chuyển sang các ô lân cận
        for action, new_pos, move_cost in get_neighbors(current_pos):
            new_state = (new_pos, remaining_dirt)
            new_cost = cost + move_cost

            if new_state not in reached or new_cost < reached[new_state]:
                reached[new_state] = new_cost
                counter += 1

                heapq.heappush(
                    frontier,
                    (
                        new_cost,
                        counter,
                        new_state,
                        path + [new_pos],
                        actions + [f"Move {action} to {new_pos}, cost={move_cost}"]
                    )
                )

    return None


# =========================
# 4. VẼ BẢN ĐỒ
# =========================

def draw_grid(robot_pos, remaining_dirt, title="Vacuum Cleaner UCS"):
    fig, ax = plt.subplots(figsize=(6, 6))

    for r in range(ROWS):
        for c in range(COLS):
            if grid[r][c] == -1:
                color = "black"
                text = "#"
                text_color = "white"
            else:
                color = "white"
                text = str(grid[r][c])
                text_color = "black"

            rect = plt.Rectangle((c, ROWS - r - 1), 1, 1, edgecolor="black", facecolor=color)
            ax.add_patch(rect)

            ax.text(
                c + 0.5,
                ROWS - r - 0.5,
                text,
                ha="center",
                va="center",
                fontsize=12,
                color=text_color
            )

    for dirt in remaining_dirt:
        r, c = dirt
        ax.text(
            c + 0.5,
            ROWS - r - 0.5,
            "D",
            ha="center",
            va="center",
            fontsize=18,
            color="brown"
        )

    rr, rc = robot_pos
    ax.text(
        rc + 0.5,
        ROWS - rr - 0.5,
        "🤖",
        ha="center",
        va="center",
        fontsize=20
    )

    ax.set_xlim(0, COLS)
    ax.set_ylim(0, ROWS)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_title(title)
    plt.show()


# =========================
# 5. CHẠY THUẬT TOÁN
# =========================

result = uniform_cost_search(start, dirt_positions)

if result is None:
    print("Không tìm thấy lời giải.")
else:
    print("TÌM THẤY LỜI GIẢI BẰNG UCS")
    print("Tổng chi phí nhỏ nhất:", result["cost"])
    print("Số bước hành động:", len(result["actions"]))

    print("\nĐường đi:")
    for i, pos in enumerate(result["path"]):
        print(f"{i}: {pos}")

    print("\nCác hành động:")
    for i, action in enumerate(result["actions"], start=1):
        print(f"{i}. {action}")


# =========================
# 6. IN LOG FRONTIER / REACHED
# =========================

print("\n===== BẢNG CHẠY TAY UCS =====")
for row in result["log"][:50]:
    print(
        f"Bước {row['Step']:02d} | "
        f"g = {row['g']:02d} | "
        f"Node = {row['Node']} | "
        f"Frontier = {row['Frontier size']} | "
        f"Reached = {row['Reached size']}"
    )

print("\nTổng số node đã xét:", len(result["log"]))


# =========================
# =========================
# 7. HIỆN TỪNG BƯỚC BẰNG NÚT BẤM
# =========================

import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import ipywidgets as widgets
import time

# Tạo dữ liệu từng bước từ result["path"] và result["actions"]
def build_step_data(result, dirt_positions):
    path = result["path"]
    actions = result["actions"]

    step_data = []
    remaining_dirt = set(dirt_positions)
    total_cost = 0

    # Step 0: trạng thái ban đầu
    step_data.append({
        "step": 0,
        "pos": path[0],
        "action": "Start",
        "cost": total_cost,
        "remaining_dirt": set(remaining_dirt)
    })

    for i in range(1, len(path)):
        prev_pos = path[i - 1]
        current_pos = path[i]

        # Nếu vị trí không đổi nghĩa là đang hút bụi
        if current_pos == prev_pos:
            total_cost += SUCK_COST
            if current_pos in remaining_dirt:
                remaining_dirt.remove(current_pos)
            action_text = f"Suck dirt at {current_pos}, cost={SUCK_COST}"
        else:
            move_cost = grid[current_pos[0]][current_pos[1]]
            total_cost += move_cost

            # Lấy action trong result nếu có
            if i - 1 < len(actions):
                action_text = actions[i - 1]
            else:
                action_text = f"Move to {current_pos}, cost={move_cost}"

        step_data.append({
            "step": i,
            "pos": current_pos,
            "action": action_text,
            "cost": total_cost,
            "remaining_dirt": set(remaining_dirt)
        })

    return step_data


step_data = build_step_data(result, dirt_positions)


def draw_step(step_info):
    robot_pos = step_info["pos"]
    remaining_dirt = step_info["remaining_dirt"]

    fig, ax = plt.subplots(figsize=(7, 7))

    for r in range(ROWS):
        for c in range(COLS):
            x = c
            y = ROWS - r - 1

            if grid[r][c] == -1:
                facecolor = "black"
                text = "#"
                text_color = "white"
            else:
                facecolor = "white"
                text = str(grid[r][c])
                text_color = "black"

            rect = plt.Rectangle(
                (x, y),
                1,
                1,
                edgecolor="black",
                facecolor=facecolor,
                linewidth=2
            )
            ax.add_patch(rect)

            ax.text(
                x + 0.5,
                y + 0.5,
                text,
                ha="center",
                va="center",
                fontsize=14,
                color=text_color
            )

    # Vẽ rác
    for dirt in remaining_dirt:
        dr, dc = dirt
        ax.text(
            dc + 0.5,
            ROWS - dr - 0.5,
            "D",
            ha="center",
            va="center",
            fontsize=22,
            color="brown",
            fontweight="bold"
        )

    # Vẽ robot bằng chữ R cho rõ
    rr, rc = robot_pos
    ax.text(
        rc + 0.5,
        ROWS - rr - 0.5,
        "R",
        ha="center",
        va="center",
        fontsize=24,
        color="red",
        fontweight="bold"
    )

    ax.set_xlim(0, COLS)
    ax.set_ylim(0, ROWS)
    ax.set_xticks([])
    ax.set_yticks([])

    ax.set_title(
        f"UCS Vacuum Cleaner - Step {step_info['step']}",
        fontsize=16,
        fontweight="bold"
    )

    plt.show()

    print("===== THÔNG TIN BƯỚC HIỆN TẠI =====")
    print("Step:", step_info["step"])
    print("Action:", step_info["action"])
    print("Robot position:", step_info["pos"])
    print("g(n) =", step_info["cost"])
    print("Remaining dirt:", sorted(list(step_info["remaining_dirt"])))

    print("\nKý hiệu:")
    print("R = Robot")
    print("D = Dirt / Rác")
    print("# = Vật cản")
    print("Số trong ô = chi phí đi vào ô đó")


# =========================
# 8. TẠO NÚT ĐIỀU KHIỂN
# =========================

current_step = 0

output = widgets.Output()

btn_prev = widgets.Button(description="◀ Previous")
btn_next = widgets.Button(description="Next ▶")
btn_auto = widgets.Button(description="Auto Run")
btn_reset = widgets.Button(description="Reset")

step_label = widgets.Label()


def update_display():
    global current_step

    with output:
        clear_output(wait=True)

        step_label.value = f"Step {current_step}/{len(step_data) - 1}"

        draw_step(step_data[current_step])


def on_prev_clicked(b):
    global current_step

    if current_step > 0:
        current_step -= 1

    update_display()


def on_next_clicked(b):
    global current_step

    if current_step < len(step_data) - 1:
        current_step += 1

    update_display()


def on_reset_clicked(b):
    global current_step

    current_step = 0
    update_display()


def on_auto_clicked(b):
    global current_step

    while current_step < len(step_data) - 1:
        current_step += 1
        update_display()
        time.sleep(0.7)


btn_prev.on_click(on_prev_clicked)
btn_next.on_click(on_next_clicked)
btn_reset.on_click(on_reset_clicked)
btn_auto.on_click(on_auto_clicked)

controls = widgets.HBox([btn_prev, btn_next, btn_auto, btn_reset])
display(widgets.VBox([step_label, controls, output]))

update_display()